"""Build an offline map from verified FDA passages to the nine Part 3 lessons."""
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[1]
s=(ROOT/'dist/catalog.js').read_text();catalog=json.JSONDecoder().raw_decode(s[s.index('{'):])[0]
ids=['nonclinical-pharmacology','nonclinical-pkpd','nonclinical-safety','nonclinical-package','cmc-material','cmc-controls','cmc-stability','clinical','clinical-dose']
lessons={l['id']:l for l in catalog['levels']}
records=[]
for group in ['nonclinical','cmc','clinical']:records+=json.loads((ROOT/f'research/lesson-map/{group}.json').read_text())
assert len({r['id'] for r in records})==len(records)
for r in records:
 assert r['lessonId'] in ids
 assert r['confidence']=='verified passage'
 assert r['pdfPages'] and all(isinstance(p,int) and p>0 for p in r['pdfPages'])
 assert r['sourceUrl'].startswith('https://')
 for secondary in r['secondaryLessonIds']:assert secondary in lessons
payload={'metadata':{'date':'2026-09-16','status':'Initial verified tranche; full FDA index screening remains in progress','assignments':len(records),'sourcePrograms':len(set(r['recordId'] for r in records)),'scope':'Selected passages from the 34-record reading library. Assignments are not counts of unique PDFs or complete INDs.'},'records':records}
(ROOT/'research/lesson-map/ind-evidence-map.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n')
(ROOT/'dist/ind-evidence-map.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n')
e=lambda x:html.escape(str(x),quote=True)
sections=[]
for id in ids:
 rows=[]
 for r in records:
  if r['lessonId']!=id:continue
  cross=' · '.join(lessons[k]['title'] for k in r['secondaryLessonIds'])
  rows.append(f'''<tr data-record="{e(r['id'])}"><th scope="row"><strong>{e(r['drug'])}</strong><small>{e(r['sourceStage'])}</small><a href="{e(r['sourceUrl'])}" target="_blank" rel="noopener noreferrer">FDA source · PDF {e(', '.join(map(str,r['pdfPages'])))} ↗</a></th><td><p>{e(r['evidenceSummary'])}</p><strong class="question">{e(r['decisionOrQuestion'])}</strong></td><td><p>{e(r['teachingUse'])}</p><details><summary>Interpretation limits</summary><p>{e(r['limitation'])}</p><p>{e(r['verificationMethod'])}</p></details>{f'<small>Also connects to: {e(cross)}</small>' if cross else ''}</td></tr>''')
 group='3A · Nonclinical evidence' if id.startswith('nonclinical') else '3B · Drug material and CMC' if id.startswith('cmc') else '3C · Clinical planning'
 sections.append(f'''<section class="lesson" id="{id}" data-lesson="{id}"><div class="lesson-heading"><div><span>{group}</span><h2>{e(lessons[id]['title'])}</h2></div><a href="index.html#small-molecule/{id}/0">Open lesson →</a></div><p class="goal">{e(lessons[id]['goal'])}</p><div class="table-wrap" role="region" tabindex="0" aria-label="Sources for {e(lessons[id]['title'])}"><table><thead><tr><th>Program and source</th><th>Evidence and decision</th><th>Use in the guide</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div></section>''')
options=''.join(f'<option value="{id}">{e(lessons[id]["title"])}</option>' for id in ids)
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FDA evidence → Part 3 lessons · First-in-Class.ai</title><style>
:root{color-scheme:light;--ink:#234f63;--line:#ccdfe7}*{box-sizing:border-box}body{margin:0;font:15px/1.75 system-ui,-apple-system,sans-serif;background:#f4f7fa;color:var(--ink)}a{color:#236780;text-underline-offset:3px}a:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #c39a46;outline-offset:3px}header{background:#23576b;color:white;padding:30px max(25px,calc((100% - 1240px)/2)) 36px}header>a{color:#cee3ec;font-size:.85rem}h1{font-size:clamp(1.7rem,3vw,2.6rem);line-height:1.25;margin:23px 0 16px;letter-spacing:-.035em}header p{max-width:890px;margin:0;color:#d7e7ef}header .count{margin-top:18px;color:#f2d59d;font-size:.86rem}main{max-width:1290px;margin:auto;padding:30px 25px 60px}.scope{max-width:980px;font-size:.9rem;color:#627b8b;margin:0 0 25px}.toolbar{display:grid;grid-template-columns:1.1fr 1fr;gap:22px;margin-bottom:18px}.toolbar label{font-size:.8rem;font-weight:600;display:grid;gap:6px}input,select{width:100%;min-height:44px;border:1px solid #b9d1dc;border-radius:7px;padding:11px;font:inherit;font-size:.9rem;background:#fff;color:var(--ink)}.status{display:flex;justify-content:space-between;gap:25px;color:#647d8c;font-size:.8rem}.lesson{margin-top:45px}.lesson-heading{display:flex;justify-content:space-between;gap:25px;align-items:center}.lesson-heading span{font-size:.75rem;color:#7c909d}.lesson-heading a{font-size:.83rem;white-space:nowrap}h2{font-size:1.45rem;line-height:1.35;letter-spacing:-.025em;margin:6px 0 0}.goal{max-width:900px;font-size:.92rem;color:#5d7686;margin:13px 0 21px}.table-wrap{overflow:auto;background:#fff;border:1px solid var(--line);border-radius:10px}table{border-collapse:collapse;width:100%;table-layout:fixed;min-width:820px;font-size:.85rem;text-align:left}thead th{padding:14px 18px;background:#e7f0f4;font-size:.77rem}thead th:first-child{width:23%}thead th:nth-child(2){width:44%}tbody th,td{vertical-align:top;padding:20px 18px;border-top:1px solid #dce8ed;font-weight:400}tbody th{background:#fafcfd}tbody th>strong{display:block;font-size:1rem}small{display:block;font-size:.74rem;line-height:1.65;color:#6c8390;margin:9px 0}tbody th>a{font-size:.75rem}td p{margin:0 0 12px;color:#4b6678}.question{font-weight:600;color:#25566d}details{font-size:.78rem;color:#6a808f}summary{cursor:pointer;color:#3c6c81}details p{margin:10px 0}footer{margin-top:45px;padding-top:20px;border-top:1px solid var(--line);color:#6a8290;font-size:.8rem}[hidden]{display:none!important}@media(max-width:650px){.toolbar{grid-template-columns:1fr}.lesson-heading{display:block}.lesson-heading>a{display:inline-block;margin-top:10px}.status{display:block}h2{font-size:1.25rem}}
</style></head><body><header><a href="fda-review-library.html">← FDA reading library</a><h1>From FDA evidence to a development decision.</h1><p>A research map for the nine lessons in IND-enabling development. Each entry identifies a source passage, the question it informs, and the limits of what we can infer.</p><p class="count">__COUNT__ verified passage assignments · nine lessons · initial research tranche</p></header><main><p class="scope">The wider FDA index search continues. This page maps selected verified passages; it is not a complete inventory of FDA IND information. A program may appear in several lessons. Earlier IND assessments, later amendments, and marketing-stage records retain their own stage labels.</p><form class="toolbar" onsubmit="return false"><label>Choose a lesson<select id="lesson-filter"><option value="all">All nine lessons</option>__OPTIONS__</select></label><label>Search the verified evidence<input id="evidence-search" type="search" placeholder="Try formulation, starting dose, study duration…"></label></form><div class="status"><span id="map-count" role="status" aria-live="polite">__COUNT__ assignments</span><a href="ind-evidence-map.json" download>Download source map · JSON</a></div>__SECTIONS__<p id="empty" hidden>No matching evidence in this tranche.</p><footer>Passage verification: 16 September 2026. PDF page numbers count from the first file page. Historical review decisions are not universal current requirements.</footer><script>
const select=document.getElementById('lesson-filter'),search=document.getElementById('evidence-search'),sections=[...document.querySelectorAll('.lesson')];
function filter(){const query=search.value.trim().toLowerCase();let total=0;for(const section of sections){let shown=0;for(const row of section.querySelectorAll('tbody tr')){row.hidden=!(select.value==='all'||section.dataset.lesson===select.value)||!row.textContent.toLowerCase().includes(query);if(!row.hidden)shown++;}section.hidden=!shown;total+=shown;}document.getElementById('map-count').textContent=total+' matching assignments';document.getElementById('empty').hidden=total>0;}
select.addEventListener('change',filter);search.addEventListener('input',filter);
</script></main></body></html>'''.replace('__COUNT__',str(len(records))).replace('__OPTIONS__',options).replace('__SECTIONS__',''.join(sections))
(ROOT/'dist/ind-evidence-map.html').write_text(page)
print(f'Built {len(records)} verified assignments across nine lessons and {payload["metadata"]["sourcePrograms"]} programs.')
