import sqlite3,gzip,json,re,fitz,hashlib,datetime
from pathlib import Path
BASE=Path('research/minireviews-development')
c=sqlite3.connect('/tmp/ind-full-screen/screen.sqlite');c.row_factory=sqlite3.Row
cache={}
def source(suffix,pages,local=None,url=None):
 r=c.execute('select * from documents where lower(url) like ? and text_file is not null',('%'+suffix.lower(),)).fetchone()
 if r:
  ps=json.load(gzip.open(r['text_file'],'rt'))['pages'];u=r['url'];path=r['text_file'];sha=r['sha256'];kind='cached PDF page extraction'
 else:
  d=fitz.open(local);ps=[p.get_text() for p in d];u=url;path=local;sha=hashlib.sha256(Path(local).read_bytes()).hexdigest();kind='original cached PDF reread'
 return {'url':u,'pdfPages':pages,'localTextOrPdf':path,'sha256':sha,'verificationMethod':kind,'pageEvidence':[{'pdfPage':p,'text':re.sub(r'\s+',' ',ps[p-1])} for p in pages]}
specs={
'oteseconazole':('215888Orig1s000IntegratedR.pdf',[127]),
'ensartinib':('218171Orig1s000AdminCorres.pdf',[49,50]),
'evinacumab':('761181Orig1s000AdminCorres.pdf',[4,5]),
'levacetylleucine':('219132Orig1s000IntegratedR.pdf',[140]),
'paltusotine':('219070Orig1s000IntegratedR.pdf',[150,151]),
'pegzilarginase-clinical':('761211Orig1s000AdminCorres.pdf',[25,27,28]),
'faricimab':('761235Orig1s000PharmR.pdf',[15,26]),
'risdiplam':('213535Orig1s000MedR.pdf',[24,25,72,73,74]),
'glofitamab':('761309Orig1s000MultidisciplineR.pdf',[36,37,50,51]),
'venetoclax':('208573Orig1s000MedR.pdf',[28,64,96],'/tmp/ind-review-library/venetoclax-clinical.pdf','https://www.accessdata.fda.gov/drugsatfda_docs/nda/2016/208573Orig1s000MedR.pdf'),
'olipudase':('761261Orig1s000IntegratedR.pdf',[52,53,132,163]),
'futibatinib':('214801Orig1s000MultidisciplineR.pdf',[35,37]),
'ivacaftor':('203188Orig1s000PharmR.pdf',[122],'/tmp/candidate-ivacaftor-fda-pharm.pdf','https://www.accessdata.fda.gov/drugsatfda_docs/nda/2012/203188Orig1s000PharmR.pdf'),
'avalglucosidase':('761194Orig1s000IntegratedR.pdf',[35,255,267,268,273,274]),
'pegzilarginase-dose':('761211Orig1s000IntegratedR.pdf',[93,192]),
'abi009':('213312Orig1s000IntegratedR.pdf',[28,42,54])}
for k,args in specs.items():cache[k]=source(*args)
# Entries are manually adjudicated; page extraction alone never determines selection.
data={
'oteseconazole':('Oteseconazole (Vivjoa)','small molecule','Initial IND2011 and later Phase2a; retrospective NDA summary','The initial IND proposed single-dose safety, tolerability and PK in healthy adults. Later Phase2a was considered exploratory and needed stronger statistical testing for definitive inference.','State which question a study can answer; early human exposure learning is distinct from definitive efficacy.','Redacted later design comments; no complete original protocol.','FDA retrospective regulatory history'),
'ensartinib':('Ensartinib (Ensacove; X-396)','small molecule','2014 IND meeting record recounting2011 pre-IND and2012 first-human study','FDA requested explicit accrual for ALK/cMET-negative tumors, adequate single/multiple-dose PK sampling, potential PD endpoints and cardiac-signal assessment. Escalation enrolled advanced solid tumors; expansion selected ALK-positive NSCLC.','Connect the enrollment hypothesis, samples and safety observations to the same scientific question.','This is later correspondence recalling early advice, not the original meeting minutes or full opening protocol.','FDA correspondence; sponsor interim results separately labeled in source'),
'evinacumab':('Evinacumab (Evkeeza)','monoclonal antibody','Later IND development,2014–2017, recounted in meeting correspondence','Rabbit embryo-fetal findings prompted a partial hold for women of childbearing potential; further data and consent revisions preceded lifting. Later adolescent inclusion was partially held for inadequately assessed neurodevelopmental risk.','Participant eligibility is revisable and population-specific rather than a permanent property of the molecule.','Not initial first-human permission. The older statement that LDL-lowering mechanism was unknown must not be treated as current mechanistic knowledge.','FDA IND correspondence'),
'levacetylleucine':('Levacetylleucine (Aqneursa)','small molecule','2018 pre-IND and2019 initial IND; retrospective NDA history','FDA distinguished an exploratory open-label proof-of-concept study from interpretable marketing efficacy evidence. Sponsor removed an extension and limited the study to six weeks before a may-proceed letter.','Investigational permission does not establish that the design will prove efficacy.','History summary does not reproduce every sponsor exchange; earlier use of racemic acetylleucine complicates first-ever-human framing.','FDA retrospective history'),
'paltusotine':('Paltusotine (Palsonify)','small molecule','Initial US IND2018 with Phase2 protocols and later IND/EOP2 advice','Studies were considered safe to proceed despite design concerns. FDA recommended placebo-controlled dose-ranging and washout; later found dose-response insufficiently established, including residual prior-treatment effects.','A biomarker measurement is only useful when its design supports an interpretable drug effect.','This initial US IND was not a first-ever-human trial. Later Phase3 comments must not be rewritten as initial safety requirements.','FDA retrospective history'),
'pegzilarginase-clinical':('Pegzilarginase (Loargys)','pegylated enzyme','Later IND127774 Phase3 planning meeting,2018','FDA distinguished duration adequate for arginine reduction from duration needed for functional improvement, requested biochemical metrics and assessable baseline functional deficits, and questioned changed Phase3 doses.','Measurement, duration and population should match the clinical claim; short PD change does not establish functional benefit.','Later development example, not the first-dose protocol. Several proposed durations and endpoints are redacted.','Original FDA meeting record'),
'faricimab':('Faricimab (Vabysmo)','bispecific antibody','Initial IND119225 assessment reproduced and summarized in BLA review','Starting0.5mg/eye supported;6mg/eye not supported because severe ocular inflammation remained unresolved. FDA would review lower-dose human findings before higher doses.','Separate a supported first dose from support for escalation; translate a hazard into a cohort-review condition.','Calendar entries in the retrospective summary are inconsistent. The sponsor ADA explanation was not accepted as resolving ocular risk. Local ocular doses are not systemic scaling examples.','Quoted original reviewer conclusions plus regulatory summary'),
'risdiplam':('Risdiplam (Evrysdi)','small molecule','Pre-IND2016 and later clinical development; first infant dosing after adult exposure','First infant single dose used conservative PBPK plus an additional factor; observed PK informed repeated dosing and exposure targets. Committees reviewed safety/PK/PD. FDA required ophthalmic surveillance while acknowledging prevention of irreversible retinal injury was not assured.','Link model uncertainty to staged observation and reassessment; define what monitoring can and cannot accomplish.','First infant exposure is not first-ever-human exposure; the dose algorithm is described retrospectively from the protocol, not an original FDA dose-approval letter.','FDA clinical review with quoted pre-IND advice and protocol description'),
'glofitamab':('Glofitamab (Columvi)','CD20/CD3 bispecific antibody','Retrospective BLA description of first-human modeling, plus later IND138178 meeting2021','Applicant model integrated monkey PK and cytokine/in-vitro data to keep predicted IL6 below a threshold; model table proposed5micrograms. Later FDA required hospitalization for dose2 in participants with any-grade CRS at dose1.','Mechanistic prediction does not replace surveillance; observed human responses change subsequent protection.','Proposed model dose is not independently verified as the administered first dose or FDA-approved starting dose. Later2.5mg step-up or labeling doses must not be confused with first-human prediction.','Applicant modeling description inside FDA review; later FDA comments separately identified'),
'venetoclax':('Venetoclax (Venclexta)','small molecule','Initial study described retrospectively; later IND110159 amendments/partial hold2011–2013','Nonclinical-based early doses were followed by tumor lysis. Protocol amendments lowered starting dose, extended ramp-up and added stratification, prophylaxis, hospitalization and lab monitoring; partial hold later lifted.','A first-dose rationale is provisional. Interpret improvement as a package of changes, not proof of one causal component.','Historical dosing, not prescribing advice. Cross-trial TLS comparisons were sponsor analyses, not independently verified by the clinical reviewer.','FDA clinical review of study and amendment history'),
'olipudase':('Olipudase alfa (Xenpozyme)','replacement enzyme','Initial IND012757 and later amendments; retrospective BLA summary','Initial hold was partly lifted for single-dose study; later repeat-dose permission had dose/interval/duration restrictions. A mouse-NOAEL-based start preceded inflammatory findings at higher single doses, leading to gradual within-person escalation.','Permission is scoped to a study; substrate biology can make stepwise exposure essential.','Retrospective history, not every original hold letter. Initial, later and commercial starting doses are different quantities.','FDA integrated review'),
'futibatinib':('Futibatinib (Lytgobi)','small molecule','Initial IND1210622013/2014 and later hold removal2017, retrospective NDA summary','Phase2 part of combined Phase1/2 study was partially held for clinical and quality concerns. Later safety, activity, expansion-dose justification and quality responses supported lifting.','Combined phase labels retain conditional evidence boundaries.','Full original hold letter and sponsor response are not reproduced; the review should not infer that every issue was purely a dose concern.','Applicant chronology plus explicit FDA assessment'),
'ivacaftor':('Ivacaftor (Kalydeco)','small molecule','Original initial IND74633 review, reproduced in2012NDA package','At proposed25mg start, surface-area margins were76–79fold; at800mg maximum about2fold. Fourteen-day studies did not identify target organs. Reviewer accepted modified500mg maximum and requested better future toxicity characterization.','A large initial margin does not determine the escalation limit or prove hazards absent.','Historical study design and numerical conversion; not a current universal rule.','Original FDA reviewer assessment'),
'avalglucosidase':('Avalglucosidase alfa (Nexviazyme)','replacement enzyme','Original July2013 preliminary IND109569 review plus later BLA summary','Original review called50mg/kg NOAEL and200mg/kg tolerated based on limited weight/organ-weight effects; tolerated-dose margins13fold at5mg/kg and3.2fold at20mg/kg. Residual free glycan qualification also mattered. Later summary calls200mg/kg NOAEL.','Distinguish observed adversity, tolerated dose and product qualification; retain source disagreements instead of manufacturing a single clean calculation.','Explicit internal discrepancy between original review and later summary; do not call200mg/kg unanimously established NOAEL.','Original FDA IND reviewer and separate retrospective clinical summary'),
'pegzilarginase-dose':('Pegzilarginase (Loargys)','pegylated enzyme','Retrospective first-human dose account; IND127774 opened2015 after earlier withdrawn IND','0.015mg/kg start related to monkey0.3mg/kg NOAEL and predicted10–11foldAUC margin. PD arginine reduction supported context; repeated doses used individual PK/arginine and did not exceed prior single-dose experience.','Keep toxicity anchor, exposure prediction and PD in parallel; use measured human data for subsequent steps.','Source uses two similar trial identifiers inconsistently; retain main named trial and flag typo. Later pivotal0.1mg/kg starting dose is not first-human0.015mg/kg.','FDA integrated review describing sponsor trial rationale'),
'abi009':('Albumin-bound sirolimus (Fyarro; ABI-009)','small molecule in albumin-bound formulation','Initial IND2006 linked to CA401; retrospective NDA dose/schedule review','45mg/m2 weekly first-human start described as about one tenth rat maximum tolerated repeat dose. Later missed third-week doses supported two-on/one-off schedule; oncology and PAH tolerability differed.','Context, schedule and formulation matter; animal reference does not eliminate need for human schedule learning.','505(b)(2) formulation/route program. Do not relabel the cited maximum tolerated repeat dose as STD10. Retrospective review contains limited original starting-dose detail.','FDA dose assessment and applicant regulatory history')}
clinical_ids=['oteseconazole','ensartinib','evinacumab','levacetylleucine','paltusotine','pegzilarginase-clinical','faricimab','risdiplam','glofitamab','venetoclax','olipudase','futibatinib']
dose_ids=['ivacaftor','faricimab','avalglucosidase','pegzilarginase-dose','abi009','glofitamab','risdiplam','olipudase','venetoclax']
for lesson,ids in [('clinical',clinical_ids),('clinical-dose',dose_ids)]:
 records=[]
 for k in ids:
  drug,mod,stage,facts,interpretation,lim,authority=data[k];s=cache[k]
  records.append({'id':k,'drug':drug,'modality':mod,'sourceUrl':s['url']+'#page='+str(s['pdfPages'][0]),'pdfPages':s['pdfPages'],'sourceStage':stage,'sourceFacts':[facts],'interpretationForLesson':interpretation,'limitations':[lim],'sourceAuthority':authority,'verificationStatus':'critical passages reread, not entire application reviewed','sources':[s]})
 out={'lessonId':lesson,'prepared':'2026-09-17','reviewType':'Focused interpretive mini-review; purposive verified cases, not exhaustive manual review','pageConvention':'one-based PDF file pages, not printed pages','distinctPrograms':len(ids),'scope':'Earlier verified cards used only as locators; critical pages reread. Additional targeted cached-text search covered7979 extracted PDFs. Fresh parent screen7979PDFs/7933hashes/467510pages includes unreviewed candidates; no full manual-review claim. See clinical-source-triage.json.','cases':records}
 json.dump(out,open(BASE/(lesson+'.json'),'w'),indent=2,ensure_ascii=False)
# Full critical evidence is embedded in the matching JSON, allowing later review even if cache is evicted.
print('clinical',len(clinical_ids),'dose',len(dose_ids),'unique source records',len(cache))
